_wandb:
    value:
        cli_version: 0.21.3
        e:
            bbgd3p69z0bgaqheiev42cctt8fkqf5a:
                args:
                    - --model_export
                    - model_export:latest
                    - --test_data
                    - data_test.csv:latest
                codePath: evaluate/run.py
                codePathLocal: run.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1006450962432"
                        used: "184128270336"
                email: yellowgem12345@gmail.com
                executable: /home/teratron7/miniconda3/envs/mlflow-08ff023f74d8dc4ccd988e8d53bd7b56325212db/bin/python
                git:
                    commit: e9d625475394274752d5170613a2016e526581d1
                    remote: https://github.com/Beaverdam2026/genre_classification.git
                host: JackPenguin
                memory:
                    total: "33533599744"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/evaluate/run.py
                python: CPython 3.13.11
                root: /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/evaluate
                startedAt: "2026-01-16T18:16:50.709323Z"
                writerId: bbgd3p69z0bgaqheiev42cctt8fkqf5a
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
