_wandb:
    value:
        cli_version: 0.21.3
        e:
            45ak6ocnnmrirt7eevj0a3qh5xlcdpgy:
                args:
                    - --file_url
                    - https://github.com/udacity/nd0821-c2-build-model-workflow-exercises/blob/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?raw=true
                    - --artifact_name
                    - raw_data.parquet
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - Data as downloaded
                codePath: download/download_data.py
                codePathLocal: download_data.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1006450962432"
                        used: "182929305600"
                email: yellowgem12345@gmail.com
                executable: /home/teratron7/miniconda3/envs/mlflow-c8796fcdf2a60e9d2d7a0e2de87ce7cf78fe7920/bin/python
                git:
                    commit: e9d625475394274752d5170613a2016e526581d1
                    remote: https://github.com/Beaverdam2026/genre_classification.git
                host: JackPenguin
                memory:
                    total: "33533599744"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/download/download_data.py
                python: CPython 3.13.11
                root: /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/download
                startedAt: "2026-01-16T18:08:02.016763Z"
                writerId: 45ak6ocnnmrirt7eevj0a3qh5xlcdpgy
        m: []
        python_version: 3.13.11
        t:
            "3":
                - 2
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
