_wandb:
    value:
        cli_version: 0.21.3
        e:
            3bkg2l179vfjutqkfyv5z5g7mcvr7ar8:
                args:
                    - --train_data
                    - data_train.csv:latest
                    - --model_config
                    - /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/outputs/2026-01-16/10-20-54/random_forest_config.yml
                    - --export_artifact
                    - model_export
                    - --random_seed
                    - "42"
                    - --val_size
                    - "0.3"
                    - --stratify
                    - genre
                codePath: random_forest/run.py
                codePathLocal: run.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1006450962432"
                        used: "184160174080"
                email: yellowgem12345@gmail.com
                executable: /home/teratron7/miniconda3/envs/mlflow-a3629828cd971ffe646011f938d3373bb5d5ef95/bin/python
                git:
                    commit: bf005e14d6852c86d51ce36960c66a1d5c016e89
                    remote: https://github.com/Beaverdam2026/genre_classification.git
                host: JackPenguin
                memory:
                    total: "33533599744"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/random_forest/run.py
                python: CPython 3.13.11
                root: /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/random_forest
                startedAt: "2026-01-16T18:21:36.690020Z"
                writerId: 3bkg2l179vfjutqkfyv5z5g7mcvr7ar8
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
export_artifact:
    value: model_export
features:
    value:
        categorical:
            - time_signature
            - key
        nlp:
            - text_feature
        numerical:
            - danceability
            - energy
            - loudness
            - speechiness
            - acousticness
            - instrumentalness
            - liveness
            - valence
            - tempo
            - duration_ms
random_forest:
    value:
        bootstrap: true
        ccp_alpha: 0
        class_weight: balanced
        criterion: gini
        max_depth: 13
        max_features: null
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0
        n_estimators: 100
        n_jobs: null
        oob_score: false
        random_state: 42
        verbose: 0
        warm_start: false
tfidf:
    value:
        max_features: 10
