_wandb:
    value:
        cli_version: 0.21.3
        e:
            7mqrsrizu2snmiohtc17lzjrzhc6x675:
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1006450962432"
                        used: "182924685312"
                email: yellowgem12345@gmail.com
                executable: /home/teratron7/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/python3.13
                git:
                    commit: e9d625475394274752d5170613a2016e526581d1
                    remote: https://github.com/Beaverdam2026/genre_classification.git
                host: JackPenguin
                memory:
                    total: "33533599744"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/teratron7/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/pytest
                python: CPython 3.13.11
                root: /mnt/68247ae7-a5d8-49e0-872f-08b1f10c1374/WGU_Documents/Term5/D501/genre_classification/check_data
                startedAt: "2026-01-16T18:03:41.696830Z"
                writerId: 7mqrsrizu2snmiohtc17lzjrzhc6x675
        m: []
        python_version: 3.13.11
        t:
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
